### ISSUE TITLE
Meu colega não me ajudaaaaaaaaaaaaaaaaa

### ISSUE THREAD

**Issue by marcel-bt** [marcel-bt/bndtc#1]
Ele larga a mala em cima da mesa, puta inferno!!!!!!!!!!!!!!!!!!!!!!! Ele traduz funk pro inglês ~.~

**Comment by vinipis** [comment]
Ain não entendi migs... >.<

**Comment by marcel-bt** [comment]
Tá vai eu te aceito do jeito que você é

**Comment by vinipis** [comment]
Te amo <3

**Comment by marcel-bt** [comment]
E eu achava que era só jesus e minha mãe 👍
